### ISSUE TITLE
Consider call-to-action for non-administrators

### ISSUE THREAD

**Issue by mackensen** [professional-web-presence/gt-renewals#1]
Logging this from the WPCampus talk: for sites where actual content editing is delegated to non-administrator roles (like editor), showing a notice that the site needs renewal with a call to action to contact the site administrators could be beneficial.

**Comment by professional-web-presence** [comment]
+1 to this idea - it should be trivial to build an additional block for privileged roles giving status and a call-to-action for renewal.

**Comment by professional-web-presence** [comment]
We've completed this on our internal repo and will create a branch and PR for this for an incremental release.

Functionality adds a widget for non-admin users noting the renewal status and admin accounts on the site. If the site is renewed, the same message is shown for admins as non-admins.

<img width="484" alt="Screen Shot 2019-08-14 at 12 42 14 PM" src="https://user-images.githubusercontent.com/47824103/63039275-f8c8fb80-be90-11e9-8629-3053b4b5e97f.png">

**Comment by professional-web-presence** [comment]
In place per https://github.com/professional-web-presence/gt-renewals/commit/09f28132ac7202102e23da18821b9e192025ad5a .
